services:
  backend:
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app:z
      # - ./app/node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 5555:5555
    command: /usr/src/app/entrypoint.sh

# volumes:
#   node_modules: