version: '3.8'

services:
  backend:
    image: leutzed/maxiapp-backend:latest
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    image: leutzed/maxiapp-frontend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

networks:
  default:
    name: maxiapp-network