version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./environment/Dockerfile.backend
    container_name: maxiapp-backend
    volumes:
      - ../app:/app:z
      # - ../app/prisma:/home/node/app/prisma:z
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=development
    #   - DATABASE_URL=file:./prisma/dev.db
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: ./environment/Dockerfile.frontend
    container_name: maxiapp-frontend
    volumes:
        - ../frontend:/app:z
        - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: maxiapp-network