FROM node:20.6.0-alpine

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

# Copia os arquivos de configuração
COPY ./frontend/*.config.* ./
COPY ./frontend/tsconfig*.json ./
COPY ./frontend/index.html ./
COPY ./frontend/src ./
COPY ./frontend/public ./

# O código abaixo é para desenvolvimento (hot-reload)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]